# Generated by Django 4.1.1 on 2024-04-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webstore", "0002_alter_webstore_webstore_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webstorerating",
            name="webstore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="webstore.webstore",
            ),
        ),
    ]
