# Generated by Django 4.1.1 on 2024-04-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webstore", "0003_alter_webstorerating_webstore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webstorerating",
            name="webstore",
            field=models.CharField(max_length=150),
        ),
    ]
