# Generated by Django 4.1.1 on 2024-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webstore", "0004_alter_webstorerating_webstore"),
    ]

    operations = [
        migrations.AddField(
            model_name="webstore",
            name="price",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
