# Generated by Django 4.1.1 on 2024-04-25 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pro_scrape", "0002_alter_scrapeddata_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapeddata",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
